### ISSUE TITLE
MaxListenersExceededWarning on nodejs@10.1

### ISSUE THREAD

**Issue by tylerbrandt** [optimizely/javascript-sdk#102]
Since nodejs@10.1, the test suite (`npm run test-travis`) has started emitting thousands of instances of:

> (node:2877) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 2 error listeners added. Use emitter.setMaxListeners() to increase limit

I am not sure if this is indicative of a real regression in nodejs production usage, but it is definitely breaking the build (https://travis-ci.org/optimizely/javascript-sdk/jobs/381767712), and can be reproduced on my Mac using `nvm install 10.1`.

This wasn't/isn't an issue on nodejs@10.0 (https://travis-ci.org/optimizely/javascript-sdk/jobs/376595175)

**Comment by mikeng13** [comment]
Tested on one of our demo apps with `@optimizely/optimizely-sdk@2.0.1` running on Node 10.1 and called some of the APIs: `activate` and `getFeatureVariableBoolean`. Everything seems to be working normally. Will look into whether it is a symptom in our test suite with mocha.

**Comment by mikeng13** [comment]
Ran `npm test` within `packages/optimizely-sdk` to completion with all tests passing. Looks like issue might be stemming from our use of Lerna at the top level repo to run tests across all packages

**Comment by aliabbasrizvi** [comment]
@mikeng13 may be good to look at why tests are failing on @tylerbrandt 's system

**Comment by spencerwilson-optimizely** [comment]
Recent tests against the current v10 release don't seem to exhibit this issue ([example](https://travis-ci.org/optimizely/javascript-sdk/jobs/418472406)). Will close this, but please reopen if you observe the issue again!
