### ISSUE TITLE
Impression events don't respect HTTPS_PROXY

### ISSUE THREAD

**Issue by Geit** [optimizely/javascript-sdk#122]
Since #98 removed the request library in favour of the stock Node HTTP implementation, the Optimizely SDK no longer supports HTTP(S) Proxies, as Node does not proxy by default (as documented here https://github.com/nodejs/node/issues/15620).

We host our feature branches on a PAAS that requires outbound HTTP connections be proxied: As a result this bug currently causes our application to crash with the error below when calling `optimizely.activate`

```Shell
   2018-06-21T16:49:56.60+0100 [APP/PROC/WEB/0] ERR events.js:183
   2018-06-21T16:49:56.60+0100 [APP/PROC/WEB/0] ERR       throw er; // Unhandled 'error' event
   2018-06-21T16:49:56.60+0100 [APP/PROC/WEB/0] ERR       ^
   2018-06-21T16:49:56.60+0100 [APP/PROC/WEB/0] ERR Error: connect ECONNREFUSED 34.228.76.60:443
   2018-06-21T16:49:56.60+0100 [APP/PROC/WEB/0] ERR     at Object._errnoException (util.js:1022:11)
   2018-06-21T16:49:56.60+0100 [APP/PROC/WEB/0] ERR     at _exceptionWithHostPort (util.js:1044:20)
   2018-06-21T16:49:56.60+0100 [APP/PROC/WEB/0] ERR     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

```

This error can't be caught, because it occurs asynchronously to the main control flow of the application, and thus causes the entire application server to crash.

**Comment by mikeng13** [comment]
Hi! Thanks for the feedback! 

We try to make very few assumptions about the environment that the SDK runs on and instead make it easy for the SDK to be configured to fit in where it is used. The issue you describe has to do with our out of the box event dispatcher. What you can do is to override the event dispatcher as described here: https://developers.optimizely.com/x/solutions/sdks/reference/?language=javascript#event-dispatcher

I've dug up our old [event dispatcher](https://github.com/optimizely/javascript-sdk/blob/79880630065de35103bf6fb58d1df8ff05c455e3/packages/optimizely-sdk/lib/plugins/event_dispatcher/index.node.js), which uses the `request` library. Feel free to copy over that dispatcher to your code and initialize the SDK with it.

**Comment by Geit** [comment]
Thanks for the workaround, we'll try implementing that in our development environments. 

However, The more important issue here is probably that the default event dispatcher throws an uncatchable exception and crashes the application server. This will occur whenever/if optimizely is unavailable for any reason (i.e. Blocked by a proxy, or some actual downtime) which should probably be fixed regardless.

**Comment by mikeng13** [comment]
👍 we will fix on our end, thanks!

**Comment by spencerwilson-optimizely** [comment]
I think what may be happening is that `http/s.request` (used [here](https://github.com/optimizely/javascript-sdk/blob/3ba71a08626d1e6960912580c13653e66be9b7ae/packages/optimizely-sdk/lib/plugins/event_dispatcher/index.node.js#L61)) returns an `http.ClientRequest`, an EventEmitter that emits an error event. Since we don't attach a handler for any error event it may emit, so we're in this case:

> If an EventEmitter does _not_ have at least one listener registered for the 'error' event, and an 'error' event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits.

(via https://nodejs.org/api/events.html#events_error_events)

So we should add an error handler immediately after requesting to catch+log any error that might have occurred.
