### ISSUE TITLE
global export

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/javascript-sdk#14]
I see that the SDK compiles a browser distributable via webpack. However, I don't see what the globally exported variable name is for the distributable. Unfortunately none of the docs show usage other than `require(...` which isn't helpful.

More specifically, if webpack's configuration option `output.library` were set explicitly, this variable name would be abundantly clear.

**Comment by mikeng13** [comment]
Thanks for bringing this up @jasonkarns. I've created an item on our backlog to address this for the next release.

**Comment by jasonkarns** [comment]
Cool! In the interim, could you share exactly what the exported variable name actually is?

**Comment by mikeng13** [comment]
We actually aren't exporting it globally. This is something we missed in our implementation, sorry! The only way to use it currently would be via CommonJS. We'll be working on exposing a global variable soon.

**Comment by jasonkarns** [comment]
How is that possible? Webpack defaults to exporting via global variable if `output.libraryTarget` isn't specified (it defaults to `var`). https://webpack.github.io/docs/configuration.html#output-librarytarget

And your current webpack config clearly does not set `libraryTarget`: https://github.com/optimizely/javascript-sdk/blob/7e1398c82011cca9290ad1fb3f3a4dc0a19865e0/webpack.config.js#L21-L24

**Comment by mikeng13** [comment]
I believe because we do not have the `output.library` option defined it is not exporting anything globally at all. 

I have a PR open for this: https://github.com/optimizely/javascript-sdk/pull/18 
Just waiting for our tests to pass in order to release it
