### ISSUE TITLE
how to build

### ISSUE THREAD

**Issue by michael-mccoy** [optimizely/javascript-sdk#151]
Hello, how can I build the javascript sdk into a bundled file?

**Comment by ricardohs35** [comment]
Hi I'm having same issue, in the README.md file says that the `npm run build` it's available, but it's not present on the `package.json`.

I would like to build Optimizely to include it into an script tag on my HTML 🙏

**Comment by ricardohs35** [comment]
Sorry about this, my mistake was I didn't checkout to the correct branch, which is `1.6.x` 😬

**Comment by spencerwilson-optimizely** [comment]
Hey @michael-mccoy and @ricardohs35 !

That's right, up through and including 2.1.2, there's an npm script `build` that populates dist/ with a variety of bundles. The docs (for 2.1.2, in particular) describe this: [here](https://github.com/optimizely/javascript-sdk/tree/v2.1.2/packages/optimizely-sdk#build-distribution-packages).

After 2.1.2, see [these docs](https://github.com/optimizely/javascript-sdk/tree/7ab119572b1103eb094a1fb29f507bd8d4855db1/packages/optimizely-sdk#usage) (currently in master). If you still have questions, please reopen this issue. Cheers!

**Comment by mauerbac** [comment]
Hi @ricardohs35 & @michael-mccoy -- this demo app might help as well -> https://github.com/optimizely/javascript-sdk-demo-app . Let me know if you have any questions or feedback :)
