### ISSUE TITLE
optimizely.UserAttribute typescript type is incorrect

### ISSUE THREAD

**Issue by jordangarcia** [optimizely/javascript-sdk#211]
Right now it's currently

```typescript
{
  [key: string]: string
}
```

should be 
```typescript
export type UserAttributes = {
  [key: string]: any
}
```

**Comment by spencerwilson-optimizely** [comment]
@nchilada is it _any_, or one of a handful of primitive types?

**Comment by nchilada** [comment]
@spencerwilson-optimizely it really is _any_ in the interface, although some SDK semantics (in most of our current audience condition matchers, for example) are rather no-op-py for values that aren't strings, booleans, or numbers.
