### ISSUE TITLE
Stop using lodash

### ISSUE THREAD

**Issue by heygrady** [optimizely/javascript-sdk#241]
Related: https://github.com/optimizely/javascript-sdk/issues/47

Using version 3.0.1. See here: https://bundlephobia.com/result?p=@optimizely/optimizely-sdk@3.0.1

- Bundle is 83.7 kB minified, 22.4 kB gzipped
- Nearly 40% of that size is lodash -- 33 kB of the bundle is lodash!
- Without lodash your bundle would be closer to 50 kB minified, a huge savings.

We're seeing that it does indeed add lodash into our final bundle. We're using latest webpack/babel. We forked our configs from [create-react-app](https://github.com/facebook/create-react-app). Removing lodash or changing how you depend on it will dramatically decrease your bundle size for all of your customers.

You aren't really using lodash that much: https://github.com/optimizely/javascript-sdk/search?q=%22require%28%27lodash%22&unscoped_q=%22require%28%27lodash%22

Options:
- You could remove lodash packages that overlap with methods available within modern browsers, such as `find`. See here: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore
- You could use the minimal lodash packages for the functionality that is hard to replace:
  - The [lodash.isfinite](https://www.npmjs.com/package/lodash.isfinite) package is much smaller  (540 B)!!
    https://bundlephobia.com/result?p=lodash.isfinite@3.3.2
- You could replace lodash packages with performance based equivalents (like [just](https://github.com/angus-c/just))

**Comment by jordangarcia** [comment]
Thanks for the feedback @heygrady.  You're quite right that lodash takes up a huge chunk of the SDK payload size.  There are quite a few integral parts of the SDK that are using lodash, it's not clear when searching but a lot of modules depends on the `lib/utils/fns/index.js` file.

Removing lodash is on our roadmap and will be accomplished as we move to modernize this codebase over to TypeScript.

**Comment by heygrady** [comment]
This should not have been closed.

**Comment by jordangarcia** [comment]
Apologies for closing, it wasn't representative of us saying we aren't going to fix it. 

We are definitely going to remove lodash.  The `lib/utils/fns/index.js` uses only the lodash methods that we need. 

We are working on a TypeScript rewrite that will remove the need for `fns/index.js` file and the `lodash` package.

I will keep the issue open until lodash is removed.

**Comment by robertpersaud** [comment]
Thanks for keeping this open. We ran into a webpack optimization issue that broke Optimizely JS-SDK. An exception was thrown for "iteratee is not a function" because we excluded shorthands feature set for lodash-webpack-plugin module. 

`new LodashModuleReplacementPlugin({
            caching: true,
            cloning: true
        }),` // breaking

`new LodashModuleReplacementPlugin({
            caching: true,
            cloning: true,
            shorthands: true
        }),` // fix

**Comment by GCheung55** [comment]
Any updates or progress on this?

**Comment by GCheung55** [comment]
@jordangarcia Is there any way for us to track the work of replacing usages of `lodash`?

I don't have too much context, so please forgive my ignorance. It seems that replacing `lodash` would be a relatively quick win, especially having found a [branch that replaces lodash](https://github.com/optimizely/javascript-sdk/tree/mcarroll/lodash-removal).

This would prevent the need to wait for a refactor/rewrite to Typescript.

**Comment by chandywerks** [comment]
This is a problem for me. I tried to use this sdk on Lambda@Edge but this package alone is way too large for the 1MB limit.

**Comment by mjc1283** [comment]
Hey all, thanks for your patience on this issue. The work is underway and you can expect lodash to be removed in our next release.

**Comment by GCheung55** [comment]
@mjc1283 Thanks for the update - which release should we expect lodash to be removed?

**Comment by mjc1283** [comment]
@GCheung55 We released [v4.0.0-alpha.1](https://www.npmjs.com/package/@optimizely/optimizely-sdk/v/4.0.0-alpha.1) which has Lodash removed. I'll leave this issue open until we release a non-alpha version with Lodash  removed.

**Comment by mikeng13** [comment]
This is now released in [v4.0.0](https://github.com/optimizely/javascript-sdk/releases/tag/v4.0.0)
