### ISSUE TITLE
Whitelisting and forced bucketing not working for feature tests inside exclusion groups

### ISSUE THREAD

**Issue by boiarqin** [optimizely/javascript-sdk#247]
## What I wanted to do
Develop and QA a feature test (which was part of an exclusion group). 

## What I expected to happen
Expected to be able to whitelist or force bucket a user id to force a variation to be shown.

Although technically the docs do not say that whitelisting takes precedence over exclusion group bucketing, they do say that "Forced bucketing variations will take precedence over ... the normal bucketed variation."
https://docs.developers.optimizely.com/full-stack/docs/set-forced-variation
https://developers.optimizely.com/x/solutions/sdks-v1/reference/index.html?language=node&platform=fullstack

## What actually happened
- Neither whitelisting nor forced bucketing worked as expected while the feature test was in the exclusion group.
- When the feature test was removed from the group, whitelisting worked as expected again.

(This does not seem to be an issue with A/B tests inside or outside of exclusion groups. My iOS developer counterparts do not seem to have encountered this issue with the objective-c-sdk.)

## Steps to reproduce
Link to repository that can reproduce the issue: <link>
1. Set up a feature test and whitelist a user id to a variation.
2. Add the feature test to an exclusion group. In our case, the exclusion group contained other feature and a/b tests. Traffic allocation for this feature test was set at 0% or 50%.
3. Changed our user id in the app and expected to see the feature variables set according to the expected variation.

## Additional Info
I believe the root cause is here: https://github.com/optimizely/javascript-sdk/blob/553e6ffa485a519ed4de399114768ff8bdcc6c5b/packages/optimizely-sdk/lib/core/decision_service/index.js#L318-L325
Because this test is in a group, the normal bucketing process happens first and determines that the user is not in the experiment (`experiment` is null). It looks like whitelisting and forced bucketing occurs in getVariation, which does not get called if `experiment` is null.

**`@optimizely/optimizely-sdk` version:** 3.0.1

Please let me know if I can provide more clarity or detail. Thank you!

**Comment by aliabbasrizvi** [comment]
@boiarqin thank you for filling such a detailed report. We will take a look and get back to you.

**Comment by aliabbasrizvi** [comment]
Hi @boiarqin 

Thank you again for reaching out to us regarding this issue. We went over this and determined that the current behavior of the SDK is the desired behavior. Here is the reason:

Let’s say there are 2 experiments (**exp_1** and **exp_2**) in a mutex group attached to a feature.
Let’s say for **exp_1**, **user_1** is whitelisted to a variation that has feature **turned on** and for **exp_2**, **user_1** is whitelisted to a variation that has feature **turned off**.
If we do not bucket first then while evaluating the feature using `isFeatureEnabled` API, the system will not be able to determine correctly if the feature should be on or off for **user_1** .

I do however think that for single experiment in group, we can possibly revisit SDK behavior to be as if experiment is not in an exclusion group. I will follow up with the team regarding this.

Hope this reasoning makes sense. I will reach out if and when we make a change to our SDK around this whitelisting behavior.

**Comment by boiarqin** [comment]
@aliabbasrizvi Thanks for the followup! I see the conflict in the situation you're describing. I don't think we have an instance of multiple experiments attached to a feature in our setup, so we wouldn't have encountered/considered this.

Do you have recommendations for a workaround?
Currently, our workaround is to ensure that during Dev/QA our feature experiment is not part of an exclusion group, and that the experiment is only added to the group once it is ready for production. However, if we have to make some code changes while the experiment is still running, it's difficult to reliably retest it.

**Comment by aliabbasrizvi** [comment]
@boiarqin you can probably try using environments. You can create another environment (say Dev) and then add experiment to group and then only start experiment in Dev and do all the Dev/QA there and then start the experiment in your product environment.
You can find information about environments here: https://docs.developers.optimizely.com/full-stack/docs/create-and-manage-environments

Another thing to try may be to add an audience to your experiment which restricts it to your Dev/QA team and test everything there and then remove the audience once it is ready for production.

Let me know if any of these work.

**Comment by aliabbasrizvi** [comment]
@boiarqin let us know if any of these suggestions worked for you.

Thanks !!

**Comment by boiarqin** [comment]
@aliabbasrizvi Thanks for the suggestions. We do use environments, but since there are some things that can't be managed by environments (e.g. exclusion group settings are going to be the same for a test regardless of environment).

For now, we are forgoing the use of exclusion groups, because of the difficulty it has presented for dev/QA and demos. But we have also discussed the possibility of ensuring unique ids for whitelisted variations and then building a solution on top of the sdk that allows us to bypass the bucketing logic.

I'll mark this issue as closed. Thank you again for the support!
