### ISSUE TITLE
Whitelisting doesn't update the User Profile Service

### ISSUE THREAD

**Issue by josemussa** [optimizely/javascript-sdk#277]
## What I wanted to do
When implementing a User Profile Service (UPS) I noticed that whitelisted users don't update the User Profile Service.

## What I expected to happen
Based on the documentation User Profile Service is updated after returning a variation, the flow goes like this:

**Return Variation** -> **Track** -> **Update UPS**

![866c238-sdk_flowchart_updated_bucketingID](https://user-images.githubusercontent.com/4422500/58087047-12271800-7bc0-11e9-97a6-e18fbf5f5812.png)

But on the code, you can see that if the user [is whitelisted](https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/lib/core/decision_service/index.js#L80) `__saveUserProfile`[ is unreachable](https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/lib/core/decision_service/index.js#L104).

**`@optimizely/optimizely-sdk` version:3.1.0**

**Comment by mjc1283** [comment]
Hi @josemussa,

Thanks for reporting this issue. Our diagram should not show user profile service as the last step for exactly the reason you provided. We see whitelisting as a temporary QA tool, and that’s why we don’t save whitelisted variation assignments to user profile service. We will update the diagram to reflect the true behavior of the SDK.

**Comment by josemussa** [comment]
Thanks @mjc1283!
