### ISSUE TITLE
Distributable is missing from npm package

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/javascript-sdk#28]
The compiled distributable is missing from the npm package.

See: https://unpkg.com/optimizely-client-sdk@1.2.1/

The entire dist dir is being ignored from npm because of .npmignore: https://github.com/optimizely/javascript-sdk/blob/master/.npmignore#L9

The .npmignore file ought to be removed (so that ignores are only listed in .gitignore in a single place, not duplicated in two files).

dist/ should be git-ignored (compiled assets are not supposed to be committed to version control)

And `dist/` should be added to the package.json's `files` array so that the compiled distributable is actually included in the published npm package. (See `npm-pack` for inspecting the contents of the tarball that is published)

**Comment by delikat** [comment]
Hi @jasonkarns, thanks for the excellent issue report! We implemented your suggestions in #30 and v1.2.2 of the SDK (including the compiled distributable) is now live on npm. Please let us know if the issue continues to persist.

**Comment by jasonkarns** [comment]
Looks good, thanks! (kinda disappointed my commits weren't merged, though. no attribution?)

**Comment by delikat** [comment]
Hi @jasonkarns. Very sorry for the confusion–it looks we were implementing a fix at the same time you were working on your pull request, and in the urgency to fix the issue we missed it. We’ll make sure you get attribution for your work in the [CHANGELOG](https://github.com/optimizely/javascript-sdk/blob/master/CHANGELOG) of the next version. Thanks for your contribution! Also, please make sure that you have signed our Contributor Licensing Agreement as described in [CONTRIBUTING](https://github.com/optimizely/javascript-sdk/blob/master/CONTRIBUTING.md).

**Comment by jasonkarns** [comment]
Ah, cool! What are the odds, :)

No worries about it, changelog attribution. Just nice to have a trail of public work on my github profile.

But since this PR went in separately, I will call out two commits are unique to my PR: 

https://github.com/optimizely/javascript-sdk/pull/29/commits/3e32326f67726f1b313d746a107c2ccdd533009d

https://github.com/optimizely/javascript-sdk/pull/29/commits/19dd4519570e2afcd0aa24f93c6d6e7ea0eef119

**Comment by delikat** [comment]
@jasonkarns Thanks for pointing that out. Feel free to sign the CLA and resubmit a pull request with just those commits.
