### ISSUE TITLE
promise-polyfill in sdk

### ISSUE THREAD

**Issue by toser** [optimizely/javascript-sdk#287]
Hey Optimizely team. First, thx for this great SDK ❤️ 

One thing we just found implementing it in my company is that you have the dependency to `promise-polyfill`. This adds up to the bundle size. IMHO adding polyfills should be the job of the application, not a library.

## How would the enhancement work?
* remove the polyfill, or
* offer a version w/o polyfills

## When would the enhancement be useful?
When the application already have a polyfill (e.g. polyfill.io)

Thx in advance! 
Toni

**Comment by mjc1283** [comment]
Hi @toser,

Thank you for submitting this issue. As you suggest, we plan to remove promise-polyfill in a future version, and leave it up to the SDK user to provide the polyfill when necessary. We will leave this issue open in the meantime. However, we do not have any timeline on when this will be released. Thanks for your patience as we address this issue.

**Comment by wosephjeber** [comment]
I second this, and like the proposal to leave it up to the application to provide a polyfill. Another idea is for the SDK to use the "ponyfill" implementation of `promise-polyfill` so as not to affect the global environment. Although then you wouldn't get the benefit of the native Promise implementation, unless you added your own implementation to conditionally reference the native `window.Promise` object or use the imported `promise-polyfill` object.

But I also second the ❤️ for your hard work on this SDK and Optimizely's fullstack solution as well.

**Comment by mjc1283** [comment]
FYI, we released [v4.0.0-alpha.1](https://www.npmjs.com/package/@optimizely/optimizely-sdk/v/4.0.0-alpha.1) which has the Promise polyfill removed. I'll leave this issue open until we release a non-alpha version with the Promise polyfill removed.

**Comment by mikeng13** [comment]
This is now released in [v4.0.0](https://github.com/optimizely/javascript-sdk/releases/tag/v4.0.0)
