### ISSUE TITLE
Two security vulnerabilities in lodash

### ISSUE THREAD

**Issue by robtpaton** [optimizely/javascript-sdk#296]
According to Snyk, lodash < 4.17.11 has two vulnerabilities, one High and one Medium:

https://app.snyk.io/vuln/SNYK-JS-LODASH-73638
https://app.snyk.io/vuln/SNYK-JS-LODASH-73639

Since the Optimizely Javascript SDK depends on lodash 4.17.10, it has also been flagged by Snyk.

Please could you bump the lodash dependency in the Optimizely Javascript SDK to 4.17.11?

Many thanks

**Comment by mikeng13** [comment]
Hi @robtpaton thanks for raising this issue! We will certainly look into upgrading.

**Comment by mikeng13** [comment]
Opening this back up until we do a release :)

**Comment by mikeng13** [comment]
Resolved with version 3.2.1: https://www.npmjs.com/package/@optimizely/optimizely-sdk/v/3.2.1
