### ISSUE TITLE
try/catch for localStorage calls

### ISSUE THREAD

**Issue by toser** [optimizely/javascript-sdk#318]
Hey Optimizely team 👋 

A small thing I encountered having Optimizely running in prod for some weeks now. I see a fair amount of these errors shown in our error logging service:
```
[OPTIMIZELY] - ERROR ${dateTime} EventProcessor: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

This is due to the fact that Google Chrome users can actively deny access to `localStorage` (see this https://bit.ly/2H0SMJ7).

## How would the enhancement work?

This is something nobody can prevent, so I would recommend to put `localStorage` calls inside a try/catch block. 

I don't know if these users are able to attend tests at all. If not, you could prevent them from being bucketed in the first place. 

## When would the enhancement be useful?

Would be nice to not see this error because no one can do anything about it.

**Comment by mikeng13** [comment]
Thanks for raising this issue! Our team will look into it and get back to you as soon as we can.

**Comment by MisterJimson** [comment]
I suggest using an in memory cache when localstorage is not useable. We do this in all our sites, common workaround.

**Comment by toser** [comment]
@MisterJimson Thanks for the suggestion. IMHO this kind of workaround is very dependent on the use case. It might work with your own code, but third party libs could depend on the persistence of the store and break. For example with Optimizely it could break your A/B tests. 
So I prefer to handle it explicitly by use case, not with a catch all workaround.

**Comment by MisterJimson** [comment]
@toser Sure, but are the A/B tests not already broken if an exception is thrown when the SDK tries to store a value?

**Comment by toser** [comment]
@MisterJimson I don't have the insights how Optimizely works here. But in general it's better to not fake a working localstorage where it's actually just a memory store. This can cause strange behavior. Then it's better to let the browser throw an error and the lib handles the error itself.

**Comment by mikechu-optimizely** [comment]
It looks like we later [added a bit of bullet-proofing around localStorage](https://github.com/optimizely/javascript-sdk/pull/781/files#diff-52d73fa3cdfcda090fcb1e454e207b5ef3deecc5955ae4f4d5fdb47205289dbfR76), if I'm reading the nature of this request. 

Of course, feel free to re-open this Issue with additional info.
