### ISSUE TITLE
Enhancement request: `.close()` should wait for in-flight requests to complete

### ISSUE THREAD

**Issue by clementallen** [optimizely/javascript-sdk#382]
## How would the enhancement work?
Currently, the `optimizely.close()` Promise will send and wait for any pending events.  However, it does not wait for the completion of events that are in the progress of being sent.

## When would the enhancement be useful?
To avoid events half way through being sent getting cancelled before sending is complete.

**`@optimizely/optimizely-sdk` version:** 3.3.2

**Comment by mjc1283** [comment]
Thanks @clementallen for filing this issue. As mentioned in #397, this functionality is available in v3.5.0. Let us know if you have any further comments or questions.
