### ISSUE TITLE
ESM and other enhancements

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/javascript-sdk#444]
## How would the enhancement work?

Optimizations to make a smaller dependency bundle. The alpha release which eliminates the lodash dependency is fantastic! There is other low-hanging fruit to make a much smaller bundle:

1. Expose an ESM entrypoing in package.json as `module`
This would allow tree-shaking and module de-duping for consumers are already have this tooling in place.
2. Provide a way to omit (or pass-in) the datafile manager. The datafile manager is virtually unnecessary when the datafile is fetched manually or side-loaded into the page. (js-sdk-datafile-manager: 25.39KB)
3. Provide a way to opt-out of the logging dependency. This dependency provides little to no value in the browser when it is either disabled in production or a simple facade around console.log in development (js-sdk-logging: 15.24KB)
4. uuid and murmurhash may already be present in consumers' bundles
5. Omit the project config schema for production builds when validation is not desirable: (project_config_schema.js 6.58KB)
6. Allow opting out of the utils package.
13kb (uncompressed) of error messages and another 14kb (uncompressed) of validations? These assertions are quite useful during development, but do not make up for their bundle-cost in production.

(File-sizes estimates generates using rollup-plugin-visualizer from optimizely-sdk at [recent master](645ea8a81656cc6b63bfc13f1a8de53a892b2b84)

## When would the enhancement be useful?

For consumers who already have module bundler infrastructure in place (webpack, rollup, etc) and could take advantage of tree-shaking and de-duping of dependencies.

**`@optimizely/optimizely-sdk` version:** 
HEAD@645ea8a81656cc6b63bfc13f1a8de53a892b2b84

**Comment by mjc1283** [comment]
Thanks for the suggestions, @jasonkarns. I think these are great ideas, and I'll discuss with the team how they can be incorporated into our roadmap.

**Comment by jasonkarns** [comment]
Closing as most of these have been addressed by https://github.com/optimizely/javascript-sdk/releases/tag/v4.0.0
