### ISSUE TITLE
optimizely-client-sdk imports optimizely-server-sdk

### ISSUE THREAD

**Issue by cesarenaldi** [optimizely/javascript-sdk#46]
Hi there,
I'm using Optimizely to run AB test on several Single Page Applications and found that `optimizely-client-sdk` imports `optimizely-server-sdk`. This was sort of unexpected but more important the final bundle size is significantly larger (see stats below)
<img width="901" alt="screen shot 2017-04-19 at 09 54 32" src="https://cloud.githubusercontent.com/assets/3353250/25172229/3d62420a-24e8-11e7-8ab4-3973670c62cf.png">

This is an extreme case but even in an average case the whole of our application code is around 64KB (I'm talking about our application code excluding external dependencies). If you compare it with the 77KB of `optimizely-server-sdk` you can easily understand that it might have a big impact on our mobile users even when we don't run experiments.

Is there any plan to fix this situation? Is there something we can do in the meantime to reduce the "optimizely" SDK size impact on our JS bundles?

**Comment by mikeng13** [comment]
Thanks for raising the issue @cesarenaldi. Yes we do have plans to make our bundle a lot smaller, we just haven't had the manpower to do it. Unfortunately I don't have any suggestions for reducing the size. I will keep you updated as we make improvements regarding the size. 

We really appreciate your feedback!

**Comment by mikeng13** [comment]
@cesarenaldi we've released a new version of the SDK that has a smaller footprint now. Please check it out and let me know your thoughts!
