### ISSUE TITLE
Imports its own lodash in a client build

### ISSUE THREAD

**Issue by nason** [optimizely/javascript-sdk#47]
We're loading this sdk in a client app via webpack. When we do our production build we get a bundle that contains two lodashes:

<img width="1615" alt="screen shot 2017-04-26 at 2 32 14 pm" src="https://cloud.githubusercontent.com/assets/4752318/25450583/5432d544-2a8d-11e7-975b-df957e451838.png">

It looks like this is coming from this require: https://github.com/optimizely/javascript-sdk/blob/master/index.js#L16

I see that you have custom lodash build there, but do we really need it for our client? Is there any way to avoid this so we bundle just one `lodash` for the browser?

I quickly tried adding:
```js
      new webpack.NormalModuleReplacementPlugin(
        /node_modules\/optimizely-server-sdk\/node_modules\/lodash\/core\.js/,
        path.resolve(nodeModulesDir, 'lodash/core.js')
      ),
```

but no luck. Thanks for your help!

**Comment by mikeng13** [comment]
@nason thanks for the feedback. We're only pulling in `lodash/core`, I am surprised you see the entire lodash bundle being brought in with our library. Are you using webpack 1 or 2? I can try it out and get back to you some time next week.

**Comment by dpix** [comment]
related: https://github.com/optimizely/node-sdk/issues/55

**Comment by mikeng13** [comment]
I believe the latest version `1.4.3` should address this issue. Going to close. Please re-open if you still see an issue on your end.
