### ISSUE TITLE
Logging methods have no effect in v4 ESM bundle

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/javascript-sdk#483]
## What I wanted to do

Change the default log level

## What I expected to happen

I expected info and debug level messages to start being written to the console
( the fetching of datafile, etc)

## What actually happened

Nothing

## Steps to reproduce

```
// foo.js
import sdk from '@optimizely/optimizely-sdk'

function createInstance() {
  sdk.setLogLevel('debug')
  return sdk.createInstance({sdkKey})
}

createInstance()
```

**`@optimizely/optimizely-sdk` version:**  4.0.0

Compiled using rollup:

```
{
  input: "foo.js",
  plugins: [
    resolve({mainFields: ['module', 'browser']}),
    common({
      namedExports: {
        '@optimizely/js-sdk-logging': [
          'ConsoleLogHandler',
          'getLogger',
          'setLogLevel',
          'LogLevel',
          'setLogHandler',
          'setErrorHandler',
          'getErrorHandler'
        ],
        '@optimizely/js-sdk-event-processor': [
          'LogTierV1EventProcessor',
          'LocalStoragePendingEventsDispatcher'
        ]
      }
    })
  ],
  ...
}
```

I further provided an invalid sdkKey to trigger ERROR level log messages. They did not log either. Nor did anything get logged when I made the sdk options argument entirely empty (`sdk.createInstance({})`)

My suspicion is that this isn't an issue with the logger at all, but more of an issue with the ESM bundle (which is new as of v4). I suspect that the logger plugin is not properly working with the js-sdk-logging external dep.

**Comment by mjc1283** [comment]
Hey @jasonkarns, I tried to reproduce this using a minimal Rollup example, but haven't had any success yet. Here's a [branch](https://github.com/optimizely/javascript-sdk/compare/mcarroll/module-example) containing my example app. Are there any differences in your Rollup configuration compared to this one?

**Comment by mjc1283** [comment]
@jasonkarns Another thing to note: the `@optimizely/js-sdk-logging` package uses a singleton log handler that's intended to be shared among all instances. If there are multiple copies of that package running in your app, then some log messages might not reach the console. I've seen this happen when working on certain subpackages, then using `npm link` to install some `@optimizely/` packages from `node_modules`, but others from my separate local repository.

**Comment by jasonkarns** [comment]
Unsure what is going on in mine, but can't repro with minimal example so closing this.

Thanks @mjc1283 for the example branch, that was helpful. Since you have it already thrown together, dropping that in the wiki would probably be 🏆
