### ISSUE TITLE
Installation triggers not-applicable peerDep warning

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/javascript-sdk#485]
## What I wanted to do

Install optimizely-sdk package

## What I expected to happen

I expected to have no warnings or errors.

## What actually happened

```
npm WARN @optimizely/js-sdk-datafile-manager@0.5.0 requires a peer of @react-native-community/async-storage@^1.2.0 but none is installed. You must install peer dependencies yourself.
```

This dependency is not applicable for projects that are not using react-native, so it should not be marked as a required peerDep. It should be optional.

## Steps to reproduce

`npm i @optimizely/optimizely-sdk@4.0.0`

**`@optimizely/optimizely-sdk` version:**  4.0.0

**Comment by zashraf1985** [comment]
React native peer dependencies have been made optional. This is fixed.
