### ISSUE TITLE
optimizely-sdk test suite is not cleaning up properly (requires dirty --exit flag for mocha)

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/javascript-sdk#487]
The optimizely-sdk test suite requires the `--exit` flag to mocha. This means the test suite is not cleaning up after itself properly.

Mocha [provides some details](https://mochajs.org/#-exit) about the flag, why it is indicative of problems, and some ways to find/fix the root cause.

I ran the following to uncover _which_ of the many test files is causing node to hang:

```
set -x; for f in lib/**/*.tests.js; do npx mocha -r esm "$f"; done
```

The problematic file is `lib/optimizely/index.tests.js` (luckily only one file is causing node to hang).

**`@optimizely/optimizely-sdk` version:** 
tested at 764135b5e8e76dcc59a1a0e8d62d523a0520cd59

**Comment by mjc1283** [comment]
Fixed, and removed `--exit` flag, in #497.
