### ISSUE TITLE
Publish non-minified bundle and/or sourcemaps.

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/javascript-sdk#57]
With only the minified bundle published, it makes debugging the minified source rather difficult. I request that the published tarball include a non-minified bundle, such that we can debug a non-minified version of the library (or at least use our own minifier so that we can generate the corresponding source map).

At the _very_ least, I would request that the sourcemap for the existing minified bundle be distributed alongside the bundle so we can at least debug with that. (preferably, both the sourcemap and non-minified bundle would be published so consumers can make their own choice.)

**Comment by caitlinrubin-optimizely** [comment]
Hi @jasonkarns we're reviewing that change and we're going to look into the travis test failures as well. Thanks!

**Comment by mikeng13** [comment]
This is now addressed in the latest 2.0 release where we publish non-minified bundles to `dist/optimizely.browser.umd.js`
