### ISSUE TITLE
[Bug] Restore exported types defined in `shared_types`

### ISSUE THREAD

**Issue by avifoxi** [optimizely/javascript-sdk#593]
## What I wanted to do

Continue to use exported types defined in https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/lib/shared_types.ts

These used to be exported from the package. We are maintaining libraries that depend on these types.

Please export them from `index.d.ts`  

## What I expected to happen

UserProfileService type should be useable as a named export.
OptimizelyConfig type should be useable as a named export.

## What actually happened
 
These types may be able to be imported - but we have to do it much more indirectly. Please continue to just export them.

**Comment by mjc1283** [comment]
@avifoxi FYI, we are planning to do another release shortly, containing the changes in #594.
