### ISSUE TITLE
programatic access to a full list of feature flags?

### ISSUE THREAD

**Issue by frehner** [optimizely/javascript-sdk#604]
Forgive me if this exists already, but I wasn't able to find anything in the documentation.

Is there a way to get programatic access to a full list of the feature flags? If not, could that be an enhancement?

(for further context, I'm using the react-sdk)

## How would the enhancement work?

Expose an api that would probably be something as simple as `getAllFeatureFlags()`. Even if it's just the name of the flags, I can then use `optimizely.isFeatureEnabled()` to get the status of the flag

## When would the enhancement be useful?

I've built a developer+PM focused tool that allows devs/PMs to see, in our app, all the toggles and their status. I am using 

`optimizely?.client?.projectConfigManager?.datafileManager?.currentDatafile?.featureFlags` 

to get that list, which admittedly is reaching into the internals and also now appears to not work anymore. 

So instead of me searching through the internals again for that list, I thought it would be better to propose a formal API for this instead 😊

**Comment by aliabbasrizvi** [comment]
@frehner can you check out [OptimizelyConfig](https://docs.developers.optimizely.com/full-stack/docs/optimizelyconfig-react) and let us know if it satisfies your use case.

**Comment by frehner** [comment]
ah yes, that works perfectly. thanks for pointing it out and your quick response 😄

**Comment by aliabbasrizvi** [comment]
Good to know that :-)
