### ISSUE TITLE
Typescript - logLevel property on createInstance config is incorrect

### ISSUE THREAD

**Issue by jrbarnard** [optimizely/javascript-sdk#614]
## What I wanted to do

Use createInstance in typescript

## What I expected to happen

For the types to support `LogLevel | string`

## What actually happened

The createInstance Config logLevel property type is incorrect. It type hints just the LogLevel enum, but it also supports a string representation of the log level which will be coerced at runtime.

Reference to types that need changing:
* https://github.com/optimizely/javascript-sdk/blob/e0158e5aa14fc3c63cb9cbb413c72fbc9b3eb467/packages/optimizely-sdk/lib/index.d.ts#L71
* https://github.com/optimizely/javascript-sdk/blob/e0158e5aa14fc3c63cb9cbb413c72fbc9b3eb467/packages/optimizely-sdk/lib/shared_types.ts#L99

## Steps to reproduce
Set up a typescript project with the optimizely sdk and attempt to use createInstance with a string logLevel.
If you cast it and run the code it will work as expect. But the type does not support the string logLevel if not casted.

**Comment by mjc1283** [comment]
Thanks @jrbarnard. Agree with your assessment - will fix this.

**Comment by yavorona** [comment]
@jrbarnard Thanks again for reporting this issue. We merged https://github.com/optimizely/javascript-sdk/pull/627 fix and released it  in [v4.4.2](https://github.com/optimizely/javascript-sdk/releases/tag/v4.4.2)
