### ISSUE TITLE
TypeScript error on readyTimeout property

### ISSUE THREAD

**Issue by castrolem** [optimizely/javascript-sdk#622]
## What I wanted to do
Run TypeScript check without issues

## What I expected to happen
No TypeScript errors from `node_modules`

## What actually happened
Using
```
import {
  OptimizelyProvider,
  createInstance,
  setLogger,
  enums as OptimizelyEnums,
} from '@optimizely/react-sdk';
```

on my render return
```
<OptimizelyProvider
        optimizely={OptimizelyClient}
        // Only block rendering up to 2.5 seconds
        timeout={INIT_TIMEOUT}
        user={this.getOptimizelyUser()}
      >
        {this.props.children}
</OptimizelyProvider>
```

```
> tsc --project tsconfig.json --noEmit --pretty

node_modules/@optimizely/optimizely-sdk/lib/optimizely/index.ts:1412:7 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

1412       readyTimeout: readyTimeout,
           ~~~~~~~~~~~~

  node_modules/@optimizely/optimizely-sdk/lib/optimizely/index.ts:98:44
    98   private readyTimeouts: { [key: string]: {readyTimeout: number; onClose:() => void} };
                                                  ~~~~~~~~~~~~
    The expected type comes from property 'readyTimeout' which is declared here on type '{ readyTimeout: number; onClose: () => void; }'
```

## Steps to reproduce
Link to repository that can reproduce the issue: <link>

**`@optimizely/optimizely-sdk` version:**  ^4.4.0

**Browser and version:** n/a

**`node` version:**  v12.13.0

**`npm` version:** 6.14.8

Versions of any other relevant tools (like module bundlers, transpilers, etc.): 

**`typescript`:**  ~3.9.5

**Comment by mjc1283** [comment]
Thanks for reporting, @castrolem. The fix for this will go out in our next release.

**Comment by castrolem** [comment]
> Thanks for reporting, @castrolem. The fix for this will go out in our next release.

Thank you so much!

**Comment by yavorona** [comment]
@castrolem  new [optimizely-sdk v4.4.3](https://github.com/optimizely/javascript-sdk/releases/tag/v4.4.3) containing the fix for this issue has been released. Thanks!
