### ISSUE TITLE
Error while using optimizely-sdk with rollup

### ISSUE THREAD

**Issue by micheledisalvatore** [optimizely/javascript-sdk#646]
## What I wanted to do
I'm trying to create a library to manage the AB testing programmatically and to do so I'm using rollup.

## What I expected to happen
I'm trying to instantiate the OptimizelySdk with `const optimizelyClientInstance = OptimizelySdk.createInstance({ datafile })` 
and I expect `optimizelyClientInstance` to be different by `null`

## What actually happened
In my case the instantiation process is getting this error `requestTracker_1.default is not a constructor` and `optimizelyClientInstance` is returning `null`

## Steps to reproduce

**`@optimizely/optimizely-sdk` version: 4.4.1** 

**Browser and version: Google Chrome 87.0.4280.141**

**`node` version: 14.4.0** 

**`yarn` version: 1.22.10** 

This the small snippet with the error

```js
import OptimizelySdk from '@optimizely/optimizely-sdk'

export const Init = async (sdkKey) => {
     const optimizelyResponse = await fetch(`https://cdn.optimizely.com/datafiles/${sdkKey}.json`)

      if (optimizelyResponse.ok) {
        const datafile = await optimizelyResponse.json()
        return OptimizelySdk.createInstance({ datafile })
      }
      return null
}
```

my rollup configuration is
```js
import strip from '@rollup/plugin-strip';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import buble from '@rollup/plugin-buble';
import babel from '@rollup/plugin-babel';
import { terser } from "rollup-plugin-terser"
import replace from '@rollup/plugin-replace'

import pkg from './package.json';

export default {
  input: 'src/index.js',
  output: [{
    file: pkg.browser,
    format: 'umd',
    name: pkg.name,
    extend: true,
    plugins: [
      terser(),
      strip({
        functions: ['console.log', 'assert.*', 'debug', 'alert'],
      }),
    ],
  }, {
    file: 'build/dev.js',
    format: 'iife',
    name: pkg.name,
    extend: true,
    sourcemap: true,
  }],
  plugins: [
    nodeResolve({
      browser: true,
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
      'process.env.APP_GRAPHQL_URI': JSON.stringify(process.env.APP_GRAPHQL_URI),
      'Object.defineProperty(exports, "__esModule"': 'Object.defineProperty({}, "__esModule"',
      delimiters: ['', ''],
    }),
    buble({ transforms: { asyncAwait: false, templateString: false } }),
    commonjs({
      ignoreGlobal: false,
      include: [/node_modules/],
    }),
    babel({
      exclude: './node_modules/**',
      babelHelpers: 'bundled',
      presets: [['@babel/preset-env', { targets: { esmodules: true } }]]
    }),
  ],
}
```

I've tested the version **using HTML script tags** and it works fine, the same code, with the same `sdkKey` could it be a problem with the rollup configuration?

**Comment by micheledisalvatore** [comment]
found a solution, instead of 
```js
import OptimizelySdk from '@optimizely/optimizely-sdk'
```

I'm using 
```js
import OptimizelySdk from '../node_modules/@optimizely/optimizely-sdk/dist/optimizely.browser.min.js'
```

so I'm quite sure that the problem is with this package, as I'm using other packages and they work fine.

**Comment by yavorona** [comment]
@micheledisalvatore Thanks for submitting the issue. I looked into it, and it seems that the issue here is in the rollup config setup. In particular, the line below:
```
'Object.defineProperty(exports, "__esModule"': 'Object.defineProperty({}, "__esModule"',
```

Seems that it is missing `)` on both sides. I changed it to
```
'Object.defineProperty(exports, "__esModule")': 'Object.defineProperty({}, "__esModule")'',
```
and was able to run the snippet code without errors. 

Please let me know if you have further questions.

**Comment by yavorona** [comment]
Closing this issue. Feel free to reach out if you have questions!
