### ISSUE TITLE
setTimeout - Argument of type 'number | undefined' is not assignable to parameter of type 'number'.

### ISSUE THREAD

**Issue by Boredude** [optimizely/javascript-sdk#654]
## What I wanted to do
Code doesn't compile with typescript 

## What I expected to happen
Code can be complied

## What actually happened
Introduces an error

![image](https://user-images.githubusercontent.com/7926261/109422982-72c6c400-79e6-11eb-8dd5-775a330c848a.png)

**`@optimizely/optimizely-sdk` version:** 

**`node` version:** 4.5.0

Versions of any other relevant tools (like module bundlers, transpilers, etc.): 

Typescript version: 3.8.0

**Comment by yavorona** [comment]
@Boredude thanks for reporting this issue! The fix has been merged and released in [optimizely-sdk v4.5.1](https://github.com/optimizely/javascript-sdk/releases/tag/v4.5.1)
