### ISSUE TITLE
Typescript Types for Browser Client

### ISSUE THREAD

**Issue by arjansingh** [optimizely/javascript-sdk#662]
## How would the enhancement work?

We typed out a bunch of the client side definitions for a Typescript product we were working on. I was wondering where we could contribute them back?

Here's the gist: 
https://gist.github.com/pwfisher/e550c8a58b052c12dd503a6f30eb8bc4

## When would the enhancement be useful?

They would provide type definitions for anyone working in a strict Typescript environment.

**Comment by Develliot** [comment]
I thought this repo was already typed

**Comment by mikechu-optimizely** [comment]
Correct @Develliot we provide a the d.ts type definitions in the [published npm package release](https://www.npmjs.com/package/@optimizely/optimizely-sdk?activeTab=code)

@arjansingh, if there's something we've missed in the release delivery, ping back here and let us know....but thanks for thinking to contribute back upstream.  Cheers.

**Comment by arjansingh** [comment]
I don't even remember filing this. 😂
