### ISSUE TITLE
Switch from @react-native-community/async-storage to @react-native-async-storage/async-storage

### ISSUE THREAD

**Issue by emmanuelbuah** [optimizely/javascript-sdk#663]
## How would the enhancement work?

@react-native-community/async-storage has be deprecated in favor of @react-native-async-storage/async-storage. Please switch the packages accordingly. Of note, @react-native-async-storage/async-storage will get updates going forward rather than @react-native-community/async-storage

![Screen Shot 2021-04-27 at 1 51 13 PM](https://user-images.githubusercontent.com/432664/116296535-f5a69980-a75f-11eb-9377-f53902ed0c2d.png)

## When would the enhancement be useful?

As soon as possible

## Steps to reproduce
Link to repository that can reproduce the issue: <link>

**`@optimizely/optimizely-sdk` version:** 

**Browser and version:**

**`node` version:** 

**`npm` version:** 

Versions of any other relevant tools (like module bundlers, transpilers, etc.):

**Comment by yavorona** [comment]
@emmanuelbuah thanks for filing this issue! We will switch to @react-native-async-storage/async-storage  in our next update soon.

**Comment by konradkukier2** [comment]
@yavorona any ETA? This is deal breaker as SDK is not usable in react native expo 40+ if you already use `@react-native-async-storage/async-storage` in your project (cannot mix up these two).

**Comment by castrolem** [comment]
@zashraf1985 just noticed your PR, I think it's missing a couple of things that I added on [this draft PR](https://github.com/optimizely/javascript-sdk/pull/667) but regardless of that, @yavorona I'm seeing some auth errors on Travis not linked to either code changes.

**Comment by konradkukier2** [comment]
Any news? @yavorona

**Comment by castrolem** [comment]
> Any news? @yavorona

https://github.com/optimizely/javascript-sdk/pull/666 was merged so I'm also looking for the next release that will contain that work.

**Comment by zashraf1985** [comment]
@castrolem @konradkukier2  If you guys are using javascript SDK directly i.e `@optimizely/optimizely-sdk`, @yavorona just released [`4.6.0`](https://www.npmjs.com/package/@optimizely/optimizely-sdk/v/4.6.0) yesterday which contains this update.

If you are using `@optimizely/react-sdk`. Give is a day or two we willl bump the version of `optimizely-sdk` there and it will be ready to go too.

**Comment by professorkolik** [comment]
@zashraf1985 Hi, any timeframe for `@optimizely/react-sdk`?

**Comment by zashraf1985** [comment]
@professorkolik We just released version [`2.6.0`](https://www.npmjs.com/package/@optimizely/react-sdk/v/2.6.0) of `@optimizely/react-sdk`. This version has this update.
