### ISSUE TITLE
React Native is installed as dependency even if the SDK is meant to be used in NodeJS

### ISSUE THREAD

**Issue by fjcero** [optimizely/javascript-sdk#697]
## How would the enhancement work?

Reduce the size of dependencies

## When would the enhancement be useful?

Currently, main issues and bugs are coming from React Native peer-dependencies https://www.npmjs.com/advisories/1769

## What I wanted to do

Reduce dependencies when not needed to avoid potential issues

## What I expected to happen

Not having React Native when using NodeJS

## Steps to reproduce

`npm install @optimizely/optimizely-sdk`

**Comment by midudev** [comment]
Also, this is bloating node_modules with huge not needed dependencies:

<img width="502" alt="CleanShot 2021-09-28 at 15 33 36@2x" src="https://user-images.githubusercontent.com/1561955/135097062-009b61be-6cef-41ac-be4f-e2025b261bf0.png">

**Comment by vanderhoop** [comment]
Any movement on this?

**Comment by mikechu-optimizely** [comment]
I _think_ when we update the `export` declarations (#836, FSSDK-8983) in the package.json, only the needed deps should come along for the ride into your bundle, shaking out un-need classes.
