### ISSUE TITLE
e.replace is not a function

### ISSUE THREAD

**Issue by fabb** [optimizely/javascript-sdk#719]
In Sentry we see a lot of Optimizely errors "e.replace is not a function". In fact so many that it eats up our Sentry event budget (~70.000 events / hour). It only happens on Firefox. We cannot reproduce the issue locally though.

In the backtrace of the Sentry issue, we see that the error is logged in this line of the `catch` block in `createInstance`:
https://github.com/optimizely/javascript-sdk/blob/v4.7.0/packages/optimizely-sdk/lib/index.browser.ts#L135

We are not sure which exact line in the huge `try{}` block throws, but when looking at the compiled code, we see that `e.replace` only occurs inside `sprintf` inside the optimizely lib (assuming that this error message is not coming from another sub-dependency): https://github.com/optimizely/javascript-sdk/blob/v4.7.0/packages/utils/src/index.ts#L93

The error message `e.replace is not a function` points to `e` (= the `format` parameter of `sprintf`) being something else than a `string`. It cannot be `undefined` either because in that case, Firefox would output the error `e is undefined`.

The only calls to `sprintf` where `format` could be something else than a `string` are:
1. in the logger in the `format` function when `data.message` is not a `string`: https://github.com/optimizely/javascript-sdk/blob/v4.7.0/packages/logging/src/logger.ts#L244-L249
2. in the `httpPollingDatafileManager` when the `urlTemplate` is not a `string`: https://github.com/optimizely/javascript-sdk/blob/v4.7.0/packages/datafile-manager/src/httpPollingDatafileManager.ts#L139 - this is unlikely though because we always provide a string from our application for the `urlTemplate` in the config.

Further investiation is needed what the actual culprit is.

**`@optimizely/optimizely-sdk` version: 4.7.0** 
**`@optimizely/react-sdk` version: 2.7.0`**

**Browser and version:**

Firefox 52-95 & Firefox Mobile 90-94

**Comment by mikechu-optimizely** [comment]
Uhhhh @mikechu-optimizely Please follow the clearly Closed PR.  Sheeze, Dude. Git it together. 🙄
