### ISSUE TITLE
Security risk by outdated json-schema version

### ISSUE THREAD

**Issue by makiri1993** [optimizely/javascript-sdk#722]
## How would the enhancement work?

Update json-schema so the security risk won't be there anymore. 

## When would the enhancement be useful?

Immediately

## Steps to reproduce
Link to repository that can reproduce the issue: <link>

After running `snyk test` I'm getting this information.

```
✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922] in json-schema@0.2.3
    introduced by @package > @optimizely/optimizely-sdk@4.5.1 > json-schema@0.2.5 and 1 other path(s)
  This issue was fixed in versions: 0.4.0
```

I created a PR for it

https://github.com/optimizely/javascript-sdk/pull/721

**Comment by zashraf1985** [comment]
The fix released

https://github.com/optimizely/javascript-sdk/releases/tag/v4.8.0
https://www.npmjs.com/package/@optimizely/optimizely-sdk/v/4.8.0
