### ISSUE TITLE
Unable initialize optimizely-sdk in nextjs Middleware

### ISSUE THREAD

**Issue by sjBao** [optimizely/javascript-sdk#743]
## What I wanted to do
I wanted to initialize optimizely-sdk in nextjs's middleware api to get variant name before the request is completed.

## What I expected to happen
I expected to be able to initialize optimizely-sdk instance and use it to get a variant name for my experiment.

## What actually happened
- optimizely-sdk failed to initialize. When I tried initializing, browser version, nextjs middleware run time lacked the xmlhttprequest and window object for the sdk to initialize correctly.
- node version also does not work since nextjs middleware is runs on the [edge runtime](https://nextjs.org/docs/api-reference/edge-runtime) and not node.

## Steps to reproduce
- Start a new next12 application. 
- Try to initialize optimizely-sdk in the middleware.

**`@optimizely/optimizely-sdk` version:** 

**Browser and version:**

**`node` version:** 

**`npm` version:** 

Versions of any other relevant tools (like module bundlers, transpilers, etc.):

**Comment by zashraf1985** [comment]
@sjBao We recently introduced `lite` bundle for edge runtimes.  `lite` bundle does not have `datafile manager`. You cannot use SDK key in this case. You will need to provide a datafile at build time. `nextjs` middleware does not support outgoing requests anyway, so there is no way to use SDK key and get the datafile on runtime. This is how you can import the `lite` bundle and the SDK should work in your use case.

```
import { createInstance } from '@optimizely/optimizely-sdk/dist/optimizely.lite.min.js'
```
If you are using Vercel platform for deployments, we recently developed an integration with vercel. This takes advantage of Vercel's `Deploy hooks` and Optimizely's `Webhooks` to auto update and rebuild the whole next JS application whenever Optimizely project configuration changes. The whole integration package can be found here. If you follow the readme, you will have a working nextJS application up and running within ten minutes that uses optimizely in the middleware and auto updates and builds the application whenever Optimizely project configuration changes. 

https://github.com/optimizely/vercel-examples/tree/main/edge-functions/feature-flag-optimizely

If you are interested to just run the optimizely code in your nextJS middleware, you can get help from this tested piece of code that we are already using with next JS middle ware.

https://github.com/optimizely/vercel-examples/blob/main/edge-functions/feature-flag-optimizely/pages/_middleware.tsx

Please let us know if this was helpful.

**Comment by sjBao** [comment]
Thanks for the reply, I'll give it a try and report back here
