### ISSUE TITLE
Getting Error on Initialization: assign to read only property 'disposeOnUpdate' of object 

### ISSUE THREAD

**Issue by sbrower07** [optimizely/javascript-sdk#748]
## What I wanted to do
When initializing Optimizely I am getting an error

## What I expected to happen
the disposedOnUpdate to not error on close

## What actually happened
I am getting the following error
Chrome: [OPTIMIZELY] - ERROR 2022-03-22T18:32:04.081Z Cannot assign to read only property 'disposeOnUpdate' of object '#<e>' logger.js:208

Firefox: [OPTIMIZELY] - ERROR 2022-03-22T19:03:53.160Z "disposeOnUpdate" is read-only logger.js:208

## Steps to reproduce
Link to repository that can reproduce the issue: <link>

This is happening after Initializing Optimizely. When I use the isFeatureEnabled it returns what I expect. 

**`@optimizely/optimizely-sdk` version:*4.9.1* 

**Browser and version:*Chrome 99.0.4844.51 and Firefox 98.0.1 *

**`node` version:** 

**`npm` version:** 

Versions of any other relevant tools (like module bundlers, transpilers, etc.):

**Comment by mikechu-optimizely** [comment]
Hi @sbrower07 

If this is still a problem for you, can you link me to your SDK instantiation code (minus the SDK Key of course)? Does this problem show if you use a different SDK Key?  

Thanks.

**Comment by raju-opti** [comment]
Closing as inactive. Please reopen if the issue still persists.
