### ISSUE TITLE
sendBeacon support for tracking events?

### ISSUE THREAD

**Issue by joshunger** [optimizely/javascript-sdk#759]
👋 Is there support for sendBeacon to send tracking events?

Reference: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon

We are missing events sometimes when we navigate quickly after calling `track`. We switched out Amplitude calls to sendBeacon which fixed the issue on our analytics side and we'd like to do the same thing with Optimizely.

**Comment by ruettenm** [comment]
We also have the same issues. Could you please please give feedback here? 

Other Companys like Google use `sendBeacon` already for event tracking. It's exactly meant for your use case.

```
It's intended to be used for sending analytics data to a web server, and avoids some of the problems with legacy techniques for sending analytics, such as the use of [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest).
```

**Comment by mikechu-optimizely** [comment]
Woah. Sorry for the delay in acknowledging. Let me discuss this during today's Standup/Planning and get some initial thoughts, especially from the primary devs and product owners.

**Comment by mikechu-optimizely** [comment]
The primary devs think this is definitely something to run a spike to research the efficiency, reliability, and how to implement `sendBeaon` into the browser context. 

The product team thinks this can fit into a QY1 or QY2 initiative. 

A Jira item is being created to prioritize.

**Comment by ruettenm** [comment]
Thanks for the feedback. We are looking forward for it. Unit you release the feature we will implement a workaround on our side using `sendBeaon` to call our server and send the metrics from it.

Do you inform us here in the ticket about the progress of the `sendBeaon` implementation?

Best regards
Matthias

**Comment by mikechu-optimizely** [comment]
I'll put a note in the Jira item to update this Issue upon milestone progress.

**Comment by iamstarkov** [comment]
@mikechu-optimizely how is the progress? I filed ticket on this matter https://feedback.optimizely.com/ideas/ODPI-I-22

**Comment by mikechu-optimizely** [comment]
@iamstarkov, Sorry for the delay in replying.  I'll link up the feedback item to the internal engineering Jira ticket (FSSDK-8752) for this.  

@russell-loube-optimizely This ticket is ready for pointing.  Can you run this through your Product prioritization and see where it fits?

**Comment by mikechu-optimizely** [comment]
We are going to move forward with updating the SDK to leverage `sendBeacon` for sending track & Advanced Audience Targeting (AAT; ODP) events.

@russell-loube-optimizely will have the Product team take this GH Issue and Aha (feedback item) and add it to their prioritization.  From there, we can give an ETA.

**Comment by adamhouten** [comment]
@mikechu-optimizely Apologies for the prod, but we've been finding the same issue as above. Is there a fresh update that I can bring back to my team?

Cheers!

**Comment by mikechu-optimizely** [comment]
No troubles for the poke 👈 😁

I still see the Jira ticket (FSSDK-8752) in the "ready for story pointing" hopper. It's been approved and just needs to be pulled into a sprint plan after assigning the points and a dev resource to do the work.  

I'll add another note to the ticket, ping @russell-loube-optimizely and the product team, and also mention it at our next stand-up.  ...see if we can push the gas pedal a little more.  I've put on my calendar to update this thread 24 July in the afternoon.

**Comment by russell-loube-optimizely** [comment]
Firefox doesn't support keep alive, so we'll be evaluating implementation with sendBeacon where needed.

**Comment by mikechu-optimizely** [comment]
Yikes. Our research was completed back on the 4th of this month.  

I've requested that a development ticket to be created off the Spike and prioritized into a coming sprint.  Our product team will be setting when to pull the work into a near-term sprint.

**Comment by mikechu-optimizely** [comment]
Async story points applied. We have a planning meeting today. I'll push to get this added to our next sprint. 

cc @russell-loube-optimizely

**Comment by mikechu-optimizely** [comment]
This #866 is out there under review now.  We'll have it merged in the next few days.

**Comment by mikechu-optimizely** [comment]
We'd love any feedback you all have @joshunger @ruettenm @iamstarkov @adamhouten

**Comment by mikechu-optimizely** [comment]
PR #866 passed code review and implementation testing. 
 
@raju-opti & I are hammering an e2e automation test that's not happy....

**Comment by mikechu-optimizely** [comment]
Looking for last 👍 from senior architect, then we'll merge #866

**Comment by mikechu-optimizely** [comment]
PR #866 has been merged.
