### ISSUE TITLE
DatafileManager: HTTP errors are not logged

### ISSUE THREAD

**Issue by fmck3516** [optimizely/javascript-sdk#784]
## What I wanted to do

Check JavaScript SDK logging when the datafile request fails due to an HTTP error. 

## What I expected to happen

Error log being written (that's what the Java SDK does in case of HTTP errors).

## What actually happened

No error log was written.

## Steps to reproduce
Link to repository that can reproduce the issue: https://github.com/fmck3516/optimizely-js-incomplete-error-logging

Proposal to fix that: https://github.com/optimizely/javascript-sdk/pull/783

**Comment by Tamara-Barum** [comment]
FSSDK-9615 to track internally
