### ISSUE TITLE
Standardize consistent usage of `public` data modifier for public methods

### ISSUE THREAD

**Issue by opti-jnguyen** [optimizely/javascript-sdk#801]
Consider standardizing the usage of `public` in public methods across the repository.

Pros:
- Readability: Easy to identify methods that are meant to be reused and publicly accessible.

Cons:
- May be excessively verbose, given `public` is already implicit for non-private/protected functions.

**Comment by opti-jnguyen** [comment]
Consider adopting a popular paradigm such as Google, GitHub, AirBnb, and Microsoft: https://codeburst.io/5-javascript-style-guides-including-airbnb-github-google-88cbc6b2b7aa

**Comment by Tamara-Barum** [comment]
Internal Ticket Created: FSSDK-9571
