### ISSUE TITLE
Improve OptimizelyConfig instantiation performance

### ISSUE THREAD

**Issue by alexZielonko** [optimizely/javascript-sdk#817]
## How would the enhancement work?

Reduce the number of times that the `OptimizelyConfig`'s instantiation iterates over the datafile's feature flag list.

### Current State Summary

1. The [OptimizelyConfig](https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/lib/core/optimizely_config/index.ts) instance iterates over each feature flag in a datafile when the constructor calls `OptimizelyConfig.getFeaturesMap`
2. [getDeliveryRules](https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/lib/core/optimizely_config/index.ts#L301) is called during each iteration, which in turn calls [getVariableIdMap](https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/lib/core/optimizely_config/index.ts#L281)
3. `getVariableIdMap` iterates over each feature flag and each feature flag's variables

That is, each feature flag iteration in `getFeaturesMap` incurs another complete iteration of the feature flags when creating the `variablesIdMap`. 

Due to the nested loop, creating an `OptimizelyConfig` instance with a hypothetical datafile containing 100 feature flags iterates over the entire feature flag list over 10,000 times. 

<details>
<summary>👈 For reference, here's the complete logic flow</summary>

#### 1. Constructor calls `OptimizelyConfig.getFeaturesMap`

https://github.com/optimizely/javascript-sdk/blob/2580ea0e097d243db7050635992ebb1e7802e2ff/packages/optimizely-sdk/lib/core/optimizely_config/index.ts#L79

#### 2. `getFeaturesMap` iterates over each feature flag

https://github.com/optimizely/javascript-sdk/blob/2580ea0e097d243db7050635992ebb1e7802e2ff/packages/optimizely-sdk/lib/core/optimizely_config/index.ts#L399-L405

#### 3. `OptimizelyConfig.getDeliveryRules` is called during each feature flag iteration

https://github.com/optimizely/javascript-sdk/blob/2580ea0e097d243db7050635992ebb1e7802e2ff/packages/optimizely-sdk/lib/core/optimizely_config/index.ts#L425-L427

#### 4. `getDeliveryRules` calls `OptimizelyConfig.getVariableIdMap`

https://github.com/optimizely/javascript-sdk/blob/2580ea0e097d243db7050635992ebb1e7802e2ff/packages/optimizely-sdk/lib/core/optimizely_config/index.ts#L307

#### 5. `getVariableIdMap` iterates over all of the feature flags again & each of the feature flag's variables

https://github.com/optimizely/javascript-sdk/blob/2580ea0e097d243db7050635992ebb1e7802e2ff/packages/optimizely-sdk/lib/core/optimizely_config/index.ts#L281-L291

</details>

---

### Proposed State

My familiarity with the optimizely-sdk's internals is limited. Based on this narrow understanding, I see a couple of ways to reduce the number of times that the `OptimizelyConfig` iterates over the feature flag list. 

<details>
<summary>👈 One option - Create a single variablesIdMap in the constructor</summary>
<br />

The constructor iterates over the features flags to generate the `featureIdVariablesMap`. This reducer's callback could be extended to simultaneously create a single `variablesIdMap`. The `variablesIdMap` can then be passed to the [getFeaturesMap](https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/lib/core/optimizely_config/index.ts#L79) call, considerably reduceing the `variablesIdMap` function's overhead.

https://github.com/optimizely/javascript-sdk/blob/2580ea0e097d243db7050635992ebb1e7802e2ff/packages/optimizely-sdk/lib/core/optimizely_config/index.ts#L72-L75
</details>

<details>
<summary>👈 Another option - Use the featureVariableIdMap to pass a specific feature's variables directly to getVariableIdMap</summary>
<br />

As `getDeliveryRules` has both the `featureVariableIdMap` and `featureId`, the feature's variables can be passed directly to `getVariableIdMap`. This removes the need to iterate over the entire feature flag list. 

https://github.com/optimizely/javascript-sdk/blob/2580ea0e097d243db7050635992ebb1e7802e2ff/packages/optimizely-sdk/lib/core/optimizely_config/index.ts#L301-L304

This enhancement might look something like,

```ts
  static getDeliveryRules(
    configObj: ProjectConfig,
    featureVariableIdMap: FeatureVariablesMap,
    featureId: string,
    experiments: Experiment[]
  ): OptimizelyExperiment[] {
    // Call `getVariableIdMap` with `featureVariableIdMap[featureId]`, an array of the feature's variables
    const variableIdMap = OptimizelyConfig.getVariableIdMap(featureVariableIdMap[featureId]);
```

```ts
  static getVariableIdMap(featureVariables: FeatureVariable[]): { [id: string]: FeatureVariable } {
    let variablesIdMap: { [id: string]: FeatureVariable } = {};

    // Iterate over the `featureVariables` rather than the entire datafile's feature flag list
    variablesIdMap = (featureVariables || []).reduce((resultMap: { [id: string]: FeatureVariable }, variable) => {
      resultMap[variable.id] = variable;
      return resultMap;
    }, {});

    return variablesIdMap;
  }
```

</details>

## When would the enhancement be useful?

This is a useful performance enhancement for all @optimizely/javascript-sdk users, but particularly those with a large number of feature flags in their datafile.

**Comment by opti-jnguyen** [comment]
Hi @alexZielonko - thanks for bringing up this enhancement proposal, love the formatting and I agree that we should be consolidating redundant iterations.

Will chat with the team on this to set up a time to double check that the enhancement proposed looks good; will follow up here afterwards. Thanks!

**Comment by Lithium366** [comment]
Thank you @opti-jnguyen if it works this fix should help a lot with performance!

**Comment by russell-loube-optimizely** [comment]
Hi @alexZielonko , I wanted to provide an update. One of our engineers has evaluated your proposed solutions. Both are technically viable and would achieve desired performance improvements. I'd like to discuss with our team this week to pick an implementation approach.

I'll respond here with any timeline updates once we size this effort and get started in earnest. Thank you.

**Comment by russell-loube-optimizely** [comment]
Hi again @alexZielonko , quick update - we have a PR open to implement the first option you shared with us currently in code review.

**Comment by alexZielonko** [comment]
Hello @russell-loube-optimizely thank you for the update. I'm looking forward to this performance enhancement and will keep an eye on the pull request.

**Comment by russell-loube-optimizely** [comment]
Hey @alexZielonko , thanks for reviewing and partnering with us on this. I see @raju-opti responded and agrees it's a sensible change.

I'll be in touch in the near future r/e delivery timelines.

**Comment by russell-loube-optimizely** [comment]
Hi @alexZielonko , you can find this performance enhancements in [Release 4.9.4](https://github.com/optimizely/javascript-sdk/releases/tag/v4.9.4)! We appreciate your collaboration on the change.

I'll go ahead and close this. Please let us know if any questions or concerns.

**Comment by alexZielonko** [comment]
Thank you @russell-loube-optimizely, I appreciate your team's support!
