### ISSUE TITLE
Make package more bundling-friendly

### ISSUE THREAD

**Issue by DullReferenceException** [optimizely/javascript-sdk#86]
I've pulled `@optimizely/optimizely-sdk` into our client-side code, and according to the webpack visualizer tool, this delta occurs in the bundle size (it uses an estimate for actuals):

```
Raw: +307.2K
Actual: +77.2K
```

I've noticed that you're distributing this library as a webpack bundle. This is a bad idea because you're bundling in dependencies that may be in common with those of the consuming app. By me simply importing `@optimizely/optimizely-sdk/lib/index.browser`, this changes the delta significantly:

```
Raw: +102.4K
Actual: +53.5K
```

This is because we're also using lodash. We're also using `uuid`, though it's a different version, so making the dependency version looser on that, we could shave off a bit more (though that library is pretty tiny).

I'd recommend changing package.json such that the entry point is not a bundled build but rather is your library. That way webpack/browserify/rollup for the consuming app can make something much smaller.

**Comment by mikeng13** [comment]
Thanks for the feedback! Totally makes sense. Will discuss with team and prioritize accordingly.

**Comment by DullReferenceException** [comment]
Appreciate it. In case it helps, I've created https://github.com/optimizely/javascript-sdk/pull/87 to move this along.

**Comment by mikeng13** [comment]
Closed with https://github.com/optimizely/javascript-sdk/pull/87

**Comment by mikeng13** [comment]
Re-opening. Will close once we have deployed the fix.

**Comment by mikeng13** [comment]
Released fix here: https://github.com/optimizely/javascript-sdk/releases/tag/v2.0.1
