### ISSUE TITLE
issue: Incorrect client engine detected

### ISSUE THREAD

**Issue by jasonrowsell** [optimizely/javascript-sdk#865]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### SDK Version

4.3.2

### Current Behavior

I'm currently using Optimizely SDK in a lambda function with a node runtime. Every time the function is invoked it logs the following errors
```
ERROR	[OPTIMIZELY] - ERROR EventProcessor: window is not defined
ERROR	[OPTIMIZELY] - ERROR INDEX_BROWSER: unable to bind optimizely.close() to page unload event: "window is not defined"
```

This error seems to be coming from the `createInstance` function in [index.browser.ts](https://github.com/optimizely/javascript-sdk/blob/f5b4b9a4f1fa02ae70b2153de3aeddb818f10e8f/lib/index.browser.ts#L137). However, I would have expected the `createInstance` function in index.node.ts to have been invoked instead. Somehow the clientEngine isn't correct. Any idea why that may be?

```ts
optimizelySDK.setLogLevel("warn");
optimizelySDK.setLogger(optimizelySDK.logging.createLogger());

export default class OptimizelyFeatureToggler implements FeatureToggler {
  private static singletonInstance?: OptimizelyFeatureToggler = undefined;

  private user = "example-user";
  private client: Client;

  public static async instance() {
    if (OptimizelyFeatureToggler.singletonInstance === undefined) {
      OptimizelyFeatureToggler.singletonInstance = new OptimizelyFeatureToggler();
      await OptimizelyFeatureToggler.singletonInstance.initialize();
    }
    return OptimizelyFeatureToggler.singletonInstance;
  }

  public isFeatureEnabled(featureToggle: string): boolean {
    return this.client.isFeatureEnabled(featureToggle, this.user);
  }

  public getFeatureVariable(featureToggle: string, featureVariable: string): unknown {
    return this.client.getFeatureVariable(featureToggle, featureVariable, this.user);
  }

  private async initialize(): Promise<void> {
    const token = await this.getOptimizelyToken();
    const datafileUrl = `https://cdn.optimizely.com/datafiles/${token}.json`;
    const datafile = await fetch(datafileUrl).then(response => response.json());
    const datafileOptions = { autoUpdate: true, updateInterval: 1000 };
    this.client = optimizelySDK.createInstance({ datafile, datafileOptions });
  }

  private getOptimizelyToken = async () => {
    const secret = await secretRetriever.retrieve(process.env.OPTIMIZELY_TOKEN || "");
    return secret.token;
  };
}
```

### Expected Behavior

I expect no error messages to be logged and for the `createInstance` function in index.node.ts to be invoked rather than in index.browser.ts

### Steps To Reproduce

Invoke lambda, observe logged errors

### SDK Type

Node

### Node Version

16.20.1

**Comment by raju-opti** [comment]
Hi. Thanks for reporting the issue. We are looking into it.

A question:
Are you using any bundler? In that case, are you bundling for proper target? For example: [setting `target: 'node'` for webpack?](https://webpack.js.org/concepts/targets/)

**Comment by jasonrowsell** [comment]
Hi @raju-opti, webpack is used for the bundler and the target is set to node

```js
module.exports = {
  mode: serverlessWebpack.lib.webpack.isLocal ? "development" : "production",
  entry: serverlessWebpack.lib.entries,
  resolve: {
    extensions: [".js", ".ts"]
  },
  optimization: {
    minimize: false
  },
  output: {
    libraryTarget: "commonjs2",
    path: path.join(__dirname, ".webpack"),
    filename: "[name].js"
  },
  externals: {
    "aws-sdk": "aws-sdk"
  },
  target: "node",
  module: {
    rules: [{ test: /\.ts/, loader: "ts-loader" }]
  },
}
```

**Comment by raju-opti** [comment]
Hi @jasonrowsell , optimizely-sdk specifies three entry points in the [package.json](https://github.com/optimizely/javascript-sdk/blob/v4.3.2/packages/optimizely-sdk/package.json)

```
"module": "dist/optimizely.browser.es.min.js",
"main": "dist/optimizely.node.min.js",
"browser": "dist/optimizely.browser.min.js",
```
As you can see, `module` and `browser` field points to browser entrypoints, and the `main` field points to node entrypoint.
Looks like we need to add 
```
module.exports = {
  //...
  resolve: {
    mainFields: ['main'],
  },
};
```
to the webpack config. 

According to [webpack documentation](https://webpack.js.org/configuration/resolve/#resolvemainfields), if we use `node` target, then the default value for `resolve.mainFields` is `['module', 'main']`, which will resolve to the browser entrypoint for optimizely-sdk. Adding the above config should make webpack resolve to the node entrypoint instead.

**Comment by jasonrowsell** [comment]
Worked like a charm, no more errors logged. Thank you very much for your help and such a quick response :)
