### ISSUE TITLE
[BUG] website points to a 404 for the changelog

### ISSUE THREAD

**Issue by Pomax** [optimizely/javascript-sdk#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK Version

n/a

### Current Behavior

https://docs.developers.optimizely.com/full-stack-experimentation/docs/javascript-node-sdk points to https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/CHANGELOG.MD but should instead be pointing to https://github.com/optimizely/javascript-sdk/blob/master/CHANGELOG.md

### Expected Behavior

n/a

### Steps To Reproduce

n/a

### SDK Type

Browser

### Node Version

n/a

### Browsers impacted

n/a

### Link

https://docs.developers.optimizely.com/full-stack-experimentation/docs/javascript-node-sdk 

### Logs

n/a

### Workaround/Solution

update the link target =)

**Comment by raju-opti** [comment]
HI @Pomax , thanks for reporting this. We are looking to get this fixed

**Comment by raju-opti** [comment]
The broken link has been fixed
