### ISSUE TITLE
[ENHANCEMENT] update readme to explain what parts are "legacy"

### ISSUE THREAD

**Issue by Pomax** [optimizely/javascript-sdk#884]
### Description

The readme currently says "This repository houses the JavaScript SDK for use with Optimizely Feature Experimentation and Optimizely Full Stack (legacy)." but going to the docs over on https://docs.developers.optimizely.com/feature-experimentation/docs/javascript-node-sdk makes it seem pretty clear that this is not a legacy project at all, but the only way to officially do Node based server side optimizely work.

It would be great to explicitly open with what use cases are considered legacy, and what their current counterparts are, before diving into the real README.md

### Benefits

clarity in docs.

**Comment by raju-opti** [comment]
Hello @Pomax , actually what is intended is the "Optimizely Full Stack" product is legacy, and "Optimizely Feature Experimentation" is the latest version of the ["full stack" experimentation product. ](https://docs.developers.optimizely.com/full-stack-experimentation/docs). It is not intended to mean that this project itself is legacy. We will look to improve the readme to reflect this. Thanks for bringing this up.

**Comment by mikechu-optimizely** [comment]
Thanks for the 👍. Closing...
