### ISSUE TITLE
[BUG] Upgrade to 4.10.0 causes createInstance to return null on cloudflare workers

### ISSUE THREAD

**Issue by cupofjoakim** [optimizely/javascript-sdk#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK Version

4.10.0

### Current Behavior

When declaring a variable with the result of `createInstance` we get `null` back.

### Expected Behavior

We expect to get a `Client` instance.

### Steps To Reproduce

1. Create a worker with the 4.10.0 sdk version
2. Run createInstance
3. Get that `null` value

### SDK Type

Browser

### Node Version

v20.8.1

### Workaround/Solution

Import `createInstance` from `@optimizely/optimizely-sdk/dist/optimizely.lite.min` instead of `@optimizely/optimizely-sdk`

### Recent Change

Yes, updating to 4.10.0 broke the expected behaviour.

**Comment by cupofjoakim** [comment]
Almost instantly after posting this issue I see that it's very vaguely mentioned that the edge examples use imports from the lite sdk in the readme. Maybe the solution here is not to fix the code, but just to make the readme explicit?

> For edge workers we require use of the Lite sdk

instead of 

> These starter kits use the Lite variant of the JavaScript SDK

**Comment by raju-opti** [comment]
Hi @cupofjoakim , yes, for edge, we need to use the lite sdk. I agree, we should make this explicit in the readme. We will look to get this done soon.

**Comment by raju-opti** [comment]
The readme has been updated
