### ISSUE TITLE
getEnabledFeatures attributes usage?

### ISSUE THREAD

**Issue by jpdevries** [optimizely/javascript-sdk#94]
Let's say we have a feature called 'PDP_video_player' and another one called 'PDP_image_carousel'. Each of them have audiences, so we'll be passing attributes to `.isFeatureEnabled`. You'll only have a chance of getting the 'PDP_video_player' if 'Experience_Has_Video' is true and you'll only have a chance of getting the 'PDP_image_carousel' if 'Experience_Has_Video' is false.

In other words, when we call `.isFeatureEnabled` for different features, we'll be passing different sets of attributes because our features have different audiences.

We go to use the undocumented `getEnabledFeatures` method:

![image](https://user-images.githubusercontent.com/592335/39969615-49dcbe38-5693-11e8-8989-7f734dc1f8a4.png)

And get unexpected results because `getEnabledFeatures` accepts an `attributes` parameter, loops through all the features, and then passes that same attributes set to each feature:

![image](https://user-images.githubusercontent.com/592335/39969628-5a4edd32-5693-11e8-9f74-a3a3a850bdad.png)

Should it rather rather accept a map of attributes keyed off feature name and then pluck the right set out each time and pass those along?

![image](https://user-images.githubusercontent.com/592335/39969635-8e3a3aba-5693-11e8-8877-a634f9a2a328.png)

**Comment by jpdevries** [comment]
Upon further review, it looks like the intent is to send a big object of all the user attributes (that span across all audiences). Is that the case?

Internally we've been keeping them namespaced by experiment / audience.

**Comment by mikeng13** [comment]
Thanks for the feedback! You are correct in that we just have a giant map that spans all audiences. It also seems like your user attributes are different at different points in time (or different parts of the codebase/request). In that case you can call `isFeatureEnabled` separately for each of those occasions and supply the most accurate set of attributes.

**Comment by mikeng13** [comment]
Closing this issue. Feel free to reach out to your support representative if you have any questions!
